-- 前触发型触发器
CREATE Trigger tri_Salary_INS
ON SC INSTEAD OF INSERT AS
IF(SELECT COUNT(*) FROM SC
WHERE Sno IN (SELECT Sno FROM INSERTED)) < 10
INSERT INTO SC SELECT * FROM INSERTED

-- 后触发型触发器
CREATE Trigger tri_Grade_AFT
ON SC AFTER INSERT,UPDATE
AS
IF EXISTS(SELECT * FROM INSERTED i JOIN DELETED d
ON i.Sno = d.Sno AND i.Cno = d.Cno
WHERE i.Grade>=60 AND d.Grade <60)
ROLLBACK